### ISSUE TITLE
Unable to connect/register with hashbang

### ISSUE THREAD

**Issue by Crazylemon64** [hashbang/hashbang.sh#140]
A couple weeks ago, I caught in the chatter that there were some hosting issues imminent, and now when I scan the hashbang API for the remaining servers, there's only de1.hashbang.sh - and when I try to use the hashbang.sh/user/create API to register an account for this last server, I hit an "internal server error". Is the project/community still alive?

**Comment by daurnimator** [comment]
Yes still alive :)
The signup script should still work....

**Comment by decentralabs** [comment]
Creating your account...  Account creation failed: {
maxUsers reached for host: de1.hashbang.sh
}

**Comment by thebalaa** [comment]
Creating your account...  Account creation failed: {
maxUsers reached for host: de1.hashbang.sh
}

**Comment by tilpner** [comment]
@thebalaa Someone has been creating [randomly named accounts on de1](https://userdb.hashbang.sh/passwd?select=name), reaching the user limit of 5000

**Comment by RyanSquared** [comment]
This should now be fixed. I've cleaned up all the junk users.

**Comment by KellerFuchs** [comment]
Issue fixed 2.5yr ago, closing

**Comment by P4z** [comment]
Hi! This issue still appears to be active.
```
 We are going to create an account with the following information

 Username: p4
 Public Key: /home/p4/.ssh/id_rsa.pub
 Host: de1.hashbang.sh

 
 Does this look correct? [Y/n] 

 Creating your account...  Account creation failed: {
maxUsers reached for host: de1.hashbang.sh
}
 
 If you think this is a bug, please report it to 
 -> https://github.com/hashbang/hashbang.sh/issues/
 
 The installer will not continue from here...
```

Could you please look into that?

CC: @RyanSquared @tilpner @KellerFuchs @daurnimator

**Comment by RyanSquared** [comment]
Registration is currently disabled due to some torrenting dickheads. If you could connect to irc.hashbang.sh and poke ryan in the #! channel I can bump up the hosts limit enough for you to register.
